# Lab 1. Exploring and visualising data with Python
Download russia_losses_equipment.csv file from [Kaggle.com](https://www.kaggle.com/datasets/piterfm/2022-ukraine-russian-war).

Select one variant for this lab using the following formula:

In [1]:
N = ord("I") % 3 + 1
f"Variant #{N}"

'Variant #2'

### Tips:
1. Use the csv.reader() function to read a csv file.
2. Skip the first line (with column headers).
3. Do not use loops or other iterative constructs to process numpy arrays. Use only slices and/or universal (vectorised) functions.
4. Create functions for tasks 3-7 of each option.

### Requirements for graphs:
- set the line type (dashed, dotted, etc.);
- graphs must be labelled;
- add a legend;
- add a grid and specify the colour and type of lines;
- add a graph title, axis labels, and axis values;
- change the graph size (for example, 8x16 inches) and resolution (for example, 100 dpi);
- save the graph as a png file.

# Task
### Variant 2. Investigation of tank losses
1. Create a function that takes a file name and a column name as a parameter and returns a numpy array with column values.
2. Using the function from the previous task, create a numpy array of the values of the ‘tank’ column.
3. Find the daily losses of tanks.
4. Find the 4 largest daily losses of tanks.
5. Determine how many tanks were destroyed in the spring of 2023.
6. Find the average number of tanks destroyed in the last 100 days of the war.
7. Create a graph of tank losses for the past year (starting from the last date in the dataset).

In [2]:
"""
Task 1. Create a function that takes a file name and a column name as a parameter 
and returns a NumPy array with the column values.
"""
import numpy as np
import csv

FILE_PATH = 'russia_losses_equipment.csv'
COLUMN_NAME = 'tank', 'date'


def extract_csv_data(file_path, column_name):
    """
    Extracts data from a CSV file based on the specified column.

    Args:
        file_path (str): The path to the CSV file.
        column_name (str): The name of the column to extract data from.

    Returns:
        numpy.ndarray: A NumPy array containing the values from the specified column.
                       If the column is 'date', the array contains `datetime64[D]` values;
                       otherwise, it contains integers.
    """
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        header = next(reader)
        column_index = header.index(column_name)
        data_list = [np.datetime64(row[column_index]) if column_name == 'date' else int(row[column_index]) for row in reader]

    return np.array(data_list, dtype='datetime64[D]' if column_name == 'date' else int)

ERROR! Session/line number was not unique in database. History logging moved to new session 14


In [3]:
"""
Task 2. Using the function from the previous task, 
create a NumPy array from the values of the ‘tank’ column in the csv file.
NumPy array is sorted in chronological order.
"""
losses = extract_csv_data(FILE_PATH, COLUMN_NAME[0])[::-1]

losses

array([  80,  146,  150,  150,  198,  211,  217,  251,  269,  285,  290,
        303,  317,  335,  353,  362,  374,  389,  404,  430,  444,  450,
        466,  476,  498,  509,  517,  530,  561,  575,  582,  586,  597,
        605,  614,  625,  631,  644,  647,  676,  684,  698,  700,  705,
        722,  725,  732,  739,  753,  756,  762,  773,  790,  802,  815,
        829,  838,  854,  873,  884,  918,  939,  970,  986, 1008, 1026,
       1048, 1062, 1077, 1092, 1110, 1122, 1130, 1145, 1170, 1187, 1195,
       1205, 1218, 1220, 1228, 1235, 1251, 1254, 1263, 1278, 1285, 1293,
       1302, 1305, 1315, 1322, 1330, 1338, 1349, 1358, 1361, 1363, 1367,
       1376, 1381, 1386, 1390, 1393, 1398, 1409, 1419, 1430, 1432, 1434,
       1440, 1449, 1456, 1465, 1468, 1477, 1496, 1496, 1504, 1507, 1511,
       1532, 1552, 1567, 1572, 1573, 1577, 1582, 1584, 1589, 1594, 1600,
       1602, 1637, 1638, 1641, 1645, 1649, 1649, 1667, 1672, 1677, 1684,
       1687, 1691, 1700, 1704, 1704, 1708, 1722, 17

In [4]:
"""
Task 3. Calculate the daily losses of tanks.
"""
daily_losses = np.diff(losses)

daily_losses

array([66,  4,  0, 48, 13,  6, 34, 18, 16,  5, 13, 14, 18, 18,  9, 12, 15,
       15, 26, 14,  6, 16, 10, 22, 11,  8, 13, 31, 14,  7,  4, 11,  8,  9,
       11,  6, 13,  3, 29,  8, 14,  2,  5, 17,  3,  7,  7, 14,  3,  6, 11,
       17, 12, 13, 14,  9, 16, 19, 11, 34, 21, 31, 16, 22, 18, 22, 14, 15,
       15, 18, 12,  8, 15, 25, 17,  8, 10, 13,  2,  8,  7, 16,  3,  9, 15,
        7,  8,  9,  3, 10,  7,  8,  8, 11,  9,  3,  2,  4,  9,  5,  5,  4,
        3,  5, 11, 10, 11,  2,  2,  6,  9,  7,  9,  3,  9, 19,  0,  8,  3,
        4, 21, 20, 15,  5,  1,  4,  5,  2,  5,  5,  6,  2, 35,  1,  3,  4,
        4,  0, 18,  5,  5,  7,  3,  4,  9,  4,  0,  4, 14,  8,  7,  1,  4,
        7, 10,  4,  5,  0,  6, 15,  3, 10,  3,  6,  6, 15, 14,  3,  7,  8,
       12,  4,  6,  3, 10,  8,  5,  7,  2,  3,  5,  7,  3,  3,  5,  7, 20,
       23, 12, 25, 15, 19,  9, 20, 15, 10, 14, 18, 15,  6,  5, 13,  6,  3,
        8,  2,  4, 11,  9, 18,  8, 13, 15, 16,  6, 13, 13, 16, 23,  3, 44,
       11, 14, 17,  6, 14

In [5]:
"""
Task 4. Find the four largest daily tank losses.
"""
largest_daily_losses = np.sort(daily_losses)[-4:][::-1]

largest_daily_losses

array([66, 55, 48, 44])

In [6]:
"""
Task 5. Calculate the number of tanks destroyed in the spring of 2023.
"""
dates = extract_csv_data(FILE_PATH, COLUMN_NAME[1])[::-1]
start_index, end_index = np.where(np.isin(dates, [np.datetime64('2023-06-01'), np.datetime64('2023-09-01')]))[0]

"""
Approach 1: Calculation of losses for the period 
as the difference between the cumulative losses at the beginning and end of the period.
"""
spring_2023_losses_a1 = losses[end_index] - losses[start_index]

"""
Approach 2: Calculation of losses for the period 
as the sum of daily losses during the period.
"""
spring_2023_losses_a2 = np.sum(daily_losses[start_index:end_index])

spring_2023_losses_a1, spring_2023_losses_a2

(np.int64(655), np.int64(655))

In [7]:
"""
Task 6. Calculate the arithmetic average value of destroyed tanks over the last 100 days of the war.
"""
last_100_days_avg_losses = np.mean(daily_losses[-100:])

last_100_days_avg_losses

np.float64(8.32)

In [8]:
"""
Task 7. Create a graph of tank losses over the past year 
(starting from the last date in the dataset).
"""
import matplotlib.pyplot as plt


def plot_graph(losses, dates):
    """
    Plots a graph of daily tank losses and saves it as an image file.

    Args:
        losses (numpy.ndarray): Array of daily tank losses.
        dates (numpy.ndarray): Array of dates corresponding to the losses.

    Returns:
        None: The function saves the graph as 'russia_tank_losses.png'.
    """
    text_color = 'midnightblue'
    title_font = {'family': 'serif',
                   'color': text_color,
                   'weight': 'bold',
                   'size': 20}
    text_font = {'family': 'serif',
                  'color': text_color,
                  'weight': 'normal',
                  'size': 16}
    x = dates
    y = losses

    plt.figure(figsize=(18, 7), 
               dpi=1000, 
               facecolor='aliceblue', 
               edgecolor=text_color, 
               linewidth=3.0)
    
    plt.plot(x, y, 
             color=text_color, 
             label='Daily tank losses', 
             linestyle='dashed')

    plt.title(label='Daily losses of Russian tanks over the last year (365 days) in the 2022 Russia Ukraine War',
              fontdict=title_font, 
              loc='center', 
              pad=20)
    plt.ylabel(ylabel='Tank Losses', 
               fontdict=text_font, 
               labelpad=15, 
               loc='center')
    plt.xlabel(xlabel='Date', 
               fontdict=text_font, 
               labelpad=15, 
               loc='center')
    plt.legend(loc='upper center', 
               labelcolor=text_color)

    plt.grid(color='lightsteelblue', 
             linestyle='--', 
             linewidth=0.5)

    y_min = np.min(y)
    y_max = np.max(y)
    plt.ylim(y_min - 10, 
             y_max + 10)

    x_max = x[np.where(y == y_max)]
    plt.annotate(f'max loss = {y_max}',
                 xy=(x_max, y_max),
                 xytext=(x_max + 10, y_max - 5),
                 arrowprops=dict(facecolor='aliceblue',
                                 shrink=0.05),
                 annotation_clip=False,
                 color=text_color)

    xticks = x[np.char.endswith(x.astype(str), '-01')]
    plt.xticks(ticks=xticks, 
               color=text_color)
    plt.yticks(color=text_color)

    plt.savefig('russia_tank_losses_over_year.png')


plot_graph(daily_losses[-365:], dates[-365:])